// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.Infrastructure;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260511145412_AutoMigration_20260511-14-54")]
    partial class AutoMigration_202605111454
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.ActiviteCommunautaire", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CalendrierCommunautaireId")
                        .HasColumnType("bigint")
                        .HasColumnName("calendrier_communautaire_id");

                    b.Property<DateTime>("DateHeure")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_heure");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("titre");

                    b.HasKey("Id");

                    b.ToTable("activites_communautaires", (string)null);
                });

            modelBuilder.Entity("backend.Models.CalendrierCommunautaire", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("region");

                    b.HasKey("Id");

                    b.ToTable("calendriers_communautaires", (string)null);
                });

            modelBuilder.Entity("backend.Models.Medicament", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AineId")
                        .HasColumnType("bigint")
                        .HasColumnName("aine_id");

                    b.Property<string>("Dosage")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("dosage");

                    b.Property<string>("Frequence")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("frequence");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Marque")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("marque");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nom");

                    b.Property<string>("UrlPhoto")
                        .HasColumnType("text")
                        .HasColumnName("url_photo");

                    b.HasKey("Id");

                    b.ToTable("medicaments", (string)null);
                });

            modelBuilder.Entity("backend.Models.PartageSuivi", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AineId")
                        .HasColumnType("bigint")
                        .HasColumnName("aine_id");

                    b.Property<string>("Autorisation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("autorisation");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<long?>("ProcheAidantId")
                        .HasColumnType("bigint")
                        .HasColumnName("proche_aidant_id");

                    b.Property<string>("ProcheEmail")
                        .HasColumnType("text")
                        .HasColumnName("proche_email");

                    b.Property<string>("Relation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("relation");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("statut");

                    b.HasKey("Id");

                    b.HasIndex("ProcheAidantId");

                    b.ToTable("partages_suivi", (string)null);
                });

            modelBuilder.Entity("backend.Models.Rappel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Actif")
                        .HasColumnType("boolean")
                        .HasColumnName("actif");

                    b.Property<DateOnly>("DateDebut")
                        .HasColumnType("date")
                        .HasColumnName("date_debut");

                    b.Property<TimeOnly>("HeureDebut")
                        .HasColumnType("time without time zone")
                        .HasColumnName("heure_debut");

                    b.Property<long?>("MedicamentId")
                        .HasColumnType("bigint")
                        .HasColumnName("medicament_id");

                    b.Property<int>("MinutesAvantRappel")
                        .HasColumnType("integer")
                        .HasColumnName("minutes_avant_rappel");

                    b.Property<long?>("RendezVousMedicalId")
                        .HasColumnType("bigint")
                        .HasColumnName("rendez_vous_medical_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("rappels", (string)null);
                });

            modelBuilder.Entity("backend.Models.RendezVousMedical", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AineId")
                        .HasColumnType("bigint")
                        .HasColumnName("aine_id");

                    b.Property<DateTime>("DateHeure")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_heure");

                    b.Property<string>("Docteur")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("docteur");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.HasKey("Id");

                    b.ToTable("rendez_vous_medicaux", (string)null);
                });

            modelBuilder.Entity("backend.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nom");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<DateTime?>("PasswordResetTokenExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("password_reset_token_expires_at_utc");

                    b.Property<string>("PasswordResetTokenHash")
                        .HasColumnType("text")
                        .HasColumnName("password_reset_token_hash");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("prenom");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("telephone");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);

                    b.HasDiscriminator<string>("type").HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("backend.Models.Aine", b =>
                {
                    b.HasBaseType("backend.Models.User");

                    b.Property<DateOnly>("DateNaissance")
                        .HasColumnType("date")
                        .HasColumnName("date_naissance");

                    b.Property<string>("Docteur")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("docteur");

                    b.Property<string>("NumeroTelephoneDocteur")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("numero_telephone_docteur");

                    b.HasDiscriminator().HasValue("Aine");
                });

            modelBuilder.Entity("backend.Models.ProcheAidant", b =>
                {
                    b.HasBaseType("backend.Models.User");

                    b.HasDiscriminator().HasValue("ProcheAidant");
                });

            modelBuilder.Entity("backend.Models.StandardUser", b =>
                {
                    b.HasBaseType("backend.Models.User");

                    b.HasDiscriminator().HasValue("User");
                });

            modelBuilder.Entity("backend.Models.ActiviteCommunautaire", b =>
                {
                    b.OwnsOne("backend.Models.Adresse", "Lieu", b1 =>
                        {
                            b1.Property<long>("ActiviteCommunautaireId")
                                .HasColumnType("bigint");

                            b1.Property<string>("CodePostal")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("lieu_code_postal");

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("lieu_numero");

                            b1.Property<string>("Province")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("lieu_province");

                            b1.Property<string>("Rue")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("lieu_rue");

                            b1.Property<string>("Ville")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("lieu_ville");

                            b1.HasKey("ActiviteCommunautaireId");

                            b1.ToTable("activites_communautaires");

                            b1.WithOwner()
                                .HasForeignKey("ActiviteCommunautaireId");
                        });

                    b.Navigation("Lieu")
                        .IsRequired();
                });

            modelBuilder.Entity("backend.Models.PartageSuivi", b =>
                {
                    b.HasOne("backend.Models.ProcheAidant", null)
                        .WithMany("Partages")
                        .HasForeignKey("ProcheAidantId");
                });

            modelBuilder.Entity("backend.Models.RendezVousMedical", b =>
                {
                    b.OwnsOne("backend.Models.Adresse", "Lieu", b1 =>
                        {
                            b1.Property<long>("RendezVousMedicalId")
                                .HasColumnType("bigint");

                            b1.Property<string>("CodePostal")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("lieu_code_postal");

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("lieu_numero");

                            b1.Property<string>("Province")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("lieu_province");

                            b1.Property<string>("Rue")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("lieu_rue");

                            b1.Property<string>("Ville")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("lieu_ville");

                            b1.HasKey("RendezVousMedicalId");

                            b1.ToTable("rendez_vous_medicaux");

                            b1.WithOwner()
                                .HasForeignKey("RendezVousMedicalId");
                        });

                    b.Navigation("Lieu")
                        .IsRequired();
                });

            modelBuilder.Entity("backend.Models.User", b =>
                {
                    b.OwnsOne("backend.Models.Adresse", "Adresse", b1 =>
                        {
                            b1.Property<long>("UserId")
                                .HasColumnType("bigint");

                            b1.Property<string>("CodePostal")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("lieu_code_postal");

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("lieu_numero");

                            b1.Property<string>("Province")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("lieu_province");

                            b1.Property<string>("Rue")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("lieu_rue");

                            b1.Property<string>("Ville")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("lieu_ville");

                            b1.HasKey("UserId");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Adresse");
                });

            modelBuilder.Entity("backend.Models.ProcheAidant", b =>
                {
                    b.Navigation("Partages");
                });
#pragma warning restore 612, 618
        }
    }
}
