// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.Infrastructure;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260413150059_AutoMigration_20260413-15-00")]
    partial class AutoMigration_202604131500
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.ActiviteCommunautaire", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CalendrierCommunautaireId")
                        .HasColumnType("bigint")
                        .HasColumnName("calendrier_communautaire_id");

                    b.Property<DateTime>("DateHeure")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_heure");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Lieu")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lieu");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("titre");

                    b.HasKey("Id");

                    b.ToTable("activites_communautaires", (string)null);
                });

            modelBuilder.Entity("backend.Models.Aine", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("adresse");

                    b.Property<DateOnly>("DateNaissance")
                        .HasColumnType("date")
                        .HasColumnName("date_naissance");

                    b.Property<string>("Docteur")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("docteur");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nom");

                    b.Property<string>("NumeroTelephoneDocteur")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("numero_telephone_docteur");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("prenom");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("telephone");

                    b.HasKey("Id");

                    b.ToTable("aines", (string)null);
                });

            modelBuilder.Entity("backend.Models.CalendrierCommunautaire", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.HasKey("Id");

                    b.ToTable("calendriers_communautaires", (string)null);
                });

            modelBuilder.Entity("backend.Models.Medicament", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AineId")
                        .HasColumnType("bigint")
                        .HasColumnName("aine_id");

                    b.Property<string>("Dosage")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("dosage");

                    b.Property<string>("Frequence")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("frequence");

                    b.Property<string>("Marque")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("marque");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nom");

                    b.HasKey("Id");

                    b.ToTable("medicaments", (string)null);
                });

            modelBuilder.Entity("backend.Models.PartageSuivi", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AineId")
                        .HasColumnType("bigint")
                        .HasColumnName("aine_id");

                    b.Property<string>("Autorisation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("autorisation");

                    b.Property<long>("ProcheAidantId")
                        .HasColumnType("bigint")
                        .HasColumnName("proche_aidant_id");

                    b.HasKey("Id");

                    b.ToTable("partages_suivi", (string)null);
                });

            modelBuilder.Entity("backend.Models.ProcheAidant", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nom");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("prenom");

                    b.Property<string>("Relation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("relation");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("telephone");

                    b.HasKey("Id");

                    b.ToTable("proches_aidants", (string)null);
                });

            modelBuilder.Entity("backend.Models.Rappel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Actif")
                        .HasColumnType("boolean")
                        .HasColumnName("actif");

                    b.Property<DateTime>("DateHeure")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_heure");

                    b.Property<long?>("MedicamentId")
                        .HasColumnType("bigint")
                        .HasColumnName("medicament_id");

                    b.Property<long?>("RendezVousMedicalId")
                        .HasColumnType("bigint")
                        .HasColumnName("rendez_vous_medical_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("rappels", (string)null);
                });

            modelBuilder.Entity("backend.Models.RendezVousMedical", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AineId")
                        .HasColumnType("bigint")
                        .HasColumnName("aine_id");

                    b.Property<DateTime>("DateHeure")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_heure");

                    b.Property<string>("Docteur")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("docteur");

                    b.Property<string>("Lieu")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lieu");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.HasKey("Id");

                    b.ToTable("rendez_vous_medicaux", (string)null);
                });

            modelBuilder.Entity("backend.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nom");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("prenom");

                    b.Property<string>("Role")
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("telephone");

                    b.HasKey("Id");

                    b.ToTable("users", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
