name: proconnectnb
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.7

dependencies:
  device_preview_plus: ^2.6.2
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.1
  flutter_localization: ^0.4.0
  flutter_localizations:
    sdk: flutter
  http: ^0.13.6
  
  image_picker: ^1.2.1
  intl: ^0.20.2
  provider: ^6.0.5
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - images/
    - assets/lang/fr.json
    - assets/lang/en.json
    - .env
