// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB09tpWcHp_juujUngerr3vp3t9igStKqM',
    appId: '1:631103498588:web:453619290bc4219a13b999',
    messagingSenderId: '631103498588',
    projectId: 'proconnectnb',
    authDomain: 'proconnectnb.firebaseapp.com',
    storageBucket: 'proconnectnb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDABfMjscrLwjcosYEijkAkD-f3eod8x7g',
    appId: '1:631103498588:android:232528e9ba33ee6513b999',
    messagingSenderId: '631103498588',
    projectId: 'proconnectnb',
    storageBucket: 'proconnectnb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMnWwR1RLaYC_izeQ7t-vQuVwroLjLlDU',
    appId: '1:631103498588:ios:6291edfc90c10f1913b999',
    messagingSenderId: '631103498588',
    projectId: 'proconnectnb',
    storageBucket: 'proconnectnb.firebasestorage.app',
    iosBundleId: 'com.example.proconnectnb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMnWwR1RLaYC_izeQ7t-vQuVwroLjLlDU',
    appId: '1:631103498588:ios:6291edfc90c10f1913b999',
    messagingSenderId: '631103498588',
    projectId: 'proconnectnb',
    storageBucket: 'proconnectnb.firebasestorage.app',
    iosBundleId: 'com.example.proconnectnb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB09tpWcHp_juujUngerr3vp3t9igStKqM',
    appId: '1:631103498588:web:3ad33bbd4886647713b999',
    messagingSenderId: '631103498588',
    projectId: 'proconnectnb',
    authDomain: 'proconnectnb.firebaseapp.com',
    storageBucket: 'proconnectnb.firebasestorage.app',
  );
}
